
public enum StatusEffectType
{
    Burn,
    MoneyLoot,
    DamageAddBoostColor_Red,
    DamageAddBoostColor_Blue,
    DamageAddBoostColor_Green,
    DamageAddBoostShiny,
    DamageMultBoostColor_Red,
    DamageMultBoostColor_Blue,
    DamageMultBoostColor_Green,
    DamageMultBoostShiny,
    ShildAddBoostColor_Red,
    ShildAddBoostColor_Blue,
    ShildAddBoostColor_Green,
    ShildAddBoostShiny,
    ShildMultBoostColor_Red,
    ShildMultBoostColor_Blue,
    ShildMultBoostColor_Green,
    ShildMultBoostShiny,
    APBoost,
    MPBoost,
    APWhenHit,
}
